name: Update IP List

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-proxyip:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 使用 Personal Access Token
        token: ${{ secrets.PAT }}
      
    - name: Extract and process IPv4 addresses
      id: extract
      run: |
        mkdir -p cmliu
        > cmliu/ip.txt
        
        declare -a API_ENDPOINTS=(
          "https://ipdb.api.030101.xyz/?type=bestcf"
          "https://addressesapi.090227.xyz/CloudFlareYes"
          "https://addressesapi.090227.xyz/ip.164746.xyz"
        )
        
        for endpoint in "${API_ENDPOINTS[@]}"; do
          echo "Fetching data from $endpoint"
          
          curl -s "$endpoint" | \
            grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | \
            awk -F'.' '
              function valid(v) { return v >= 0 && v <= 255 }
              valid($1) && valid($2) && valid($3) && valid($4) { print $1"."$2"."$3"."$4 }
            ' >> cmliu/ip.txt
        done
        
        sort -u cmliu/ip.txt -o cmliu/ip.txt
        IP_COUNT=$(wc -l < cmliu/ip.txt)
        echo "ip_count=$IP_COUNT" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      run: |
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        git add cmliu/ip.txt
        git commit -m "Update IP list: $(date '+%Y-%m-%d %H:%M:%S UTC')"
        
        # 使用 PAT 推送
        git push https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

    - name: Show results
      run: |
        echo "Updated IP list with ${{ steps.extract.outputs.ip_count }} unique IPv4 addresses"
        echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S UTC')"
